*Ex27_Do_Loops_Different_Flavors.sas (Part 1);
* Assess the Effect of having no OUTPUT statement before the END statement;
options nocenter nodate nonumber;
data have1;
 do i=1 to 5;
 end;
run;
title1 'From a data set created with no OUTPUT statement before the END statement ';
proc print data=have1;
run;

*Ex27_Do_Loops_Different_Flavors.sas (Part 2);
* Assess the Effect of having  an OUTPUT statement before the END statement;
options nocenter nodate nonumber;
data have2;
 do i=1 to 5;
 output;
end;
run;
title1 'From a data set created with an OUTPUT statement before the END statement';
proc print data=have2 noobs;
run;

*Ex27_Do_Loops_Different_Flavors.sas (Part 3);
* Assess the Effect of having an nested do loop in an existing data table;
options nocenter nodate nonumber;
data class;
 set sashelp.class;
 do j=1 to 2;
  some_date=put('30Jan2018'd+ j, date9.);
  output;
 end;
run;
title1 'From a data set created with nested do loop in an existing data table';
proc print data=class (obs=10);
run;
title1;
